# Generated by Django 4.1.2 on 2022-10-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=500)),
                ("additional_link", models.URLField()),
            ],
            options={"verbose_name_plural": "Projects",},
        ),
    ]
