# Generated by Django 4.1.2 on 2022-10-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_courseracertifications_img"),
        ("projects", "0002_alter_projects_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="additional_img1",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="projects",
            name="skills",
            field=models.ManyToManyField(default=None, to="blog.skills"),
        ),
    ]
