# Generated by Django 4.1.2 on 2022-10-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_courseracertifications_img"),
        ("projects", "0003_projects_additional_img1_projects_skills"),
    ]

    operations = [
        migrations.RemoveField(model_name="projects", name="skills",),
        migrations.AddField(
            model_name="projects",
            name="skills_learned",
            field=models.ManyToManyField(to="blog.skills"),
        ),
    ]
