# Generated by Django 4.1.2 on 2022-10-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_projects_skills_projects_skills_learned"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="position",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
