# Generated by Django 3.2.6 on 2022-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='additional_img1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Images'),
        ),
    ]
