# Generated by Django 4.1.2 on 2022-10-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AwardingInstitutions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("website", models.URLField()),
            ],
            options={"verbose_name_plural": "Awarding Institutions",},
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=200)),
                ("additional_link", models.URLField()),
            ],
            options={"verbose_name_plural": "Skills",},
        ),
        migrations.CreateModel(
            name="Certifications",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "awarding_institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.awardinginstitutions",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Certifications",},
        ),
        migrations.AddField(
            model_name="awardinginstitutions",
            name="skills_learned",
            field=models.ManyToManyField(to="blog.skills"),
        ),
    ]
