# Generated by Django 4.1.2 on 2022-10-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awardinginstitutions", name="skills_learned",
        ),
        migrations.AddField(
            model_name="certifications",
            name="skills_learned",
            field=models.ManyToManyField(to="blog.skills"),
        ),
    ]
