# Generated by Django 4.1.2 on 2022-10-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_awardinginstitutions_skills_learned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseraCertifications",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("week_1", models.TextField(max_length=500)),
                ("week_2", models.TextField(max_length=500)),
                ("week_3", models.TextField(max_length=500)),
                ("week_4", models.TextField(max_length=500)),
                (
                    "awarding_institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.awardinginstitutions",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Coursera Certifications",},
        ),
        migrations.AlterField(
            model_name="skills",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.DeleteModel(name="Certifications",),
        migrations.AddField(
            model_name="courseracertifications",
            name="skills_learned",
            field=models.ManyToManyField(to="blog.skills"),
        ),
    ]
