# Generated by Django 4.1.2 on 2022-10-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_courseracertifications_alter_skills_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseracertifications", old_name="week_1", new_name="topic_1",
        ),
        migrations.RenameField(
            model_name="courseracertifications", old_name="week_2", new_name="topic_2",
        ),
        migrations.RenameField(
            model_name="courseracertifications", old_name="week_3", new_name="topic_3",
        ),
        migrations.RemoveField(model_name="courseracertifications", name="week_4",),
    ]
