# Generated by Django 4.1.2 on 2022-10-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_week_1_courseracertifications_topic_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseracertifications",
            name="img",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
