# Generated by Django 3.2.6 on 2022-10-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_courseracertifications_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseracertifications',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
